### ISSUE TITLE
Create cli-tutorial-helper module

### ISSUE THREAD

**Issue by vansimke** [dojo/meta#139] opened 2017-01-23 13:13 UTC
One of the use cases that the Dojo 2 website should support is to allow users to download any tutorial so that they can explore it locally. To support this, a new cli module should be created that exposes commands that allow a user to install a specific demonstration app along with all of its dependencies so that the user can immediately build and run it locally.

**Comment by rishson** [comment] 2017-01-23 13:19
So this might be as simple as a `cli` command that does:
```
[in tutorials dir]
>dojo tutorial 2
```
would do something like
```
git clone git@github.com:dojo/tutorials/tutorial2.git
npm i && typings i
dojo build -w
[output that tutorial 2 is available at localhost:9999 etc]
```

**Comment by edhager** [comment] 2017-02-03 00:02
If I am looking at dojo/cli correctly, a command needs a "group" and a "name".  For dojo/cli-create-app, the group is "create" and the name is "app".  Sticking with the current implementation of dojo/cli, I need a group and a name for this new command.

I figure the "name" can be "tutorial" but I'm not sure about the "group".  Here are some choices:
- install
- create
- download
- copy (I would use this if we clone the repo and then detach it by removing the .git directory)
- clone

Also, do we want the tutorial identifier to be another  argument like:
```
dojo copy tutorial 2
```
Or do we prefer an option flag like:
```
dojo copy tutorial -n 2
dojo copy tutorial -n store
```
I guess that could lead to something like:
```
dojo copy tutorial -git git@github.com:dojo/tutorials/tutorial2.git
```
Thinking about that last option, is "tutorial" the right name for this?  What about 
```
dojo copy app -git git@github.com:dojo/tutorials/tutorial2.git
dojo copy app -git git@github.com:edhager/myCoolDojoApp.git
```

**Comment by agubler** [comment] 2017-02-03 10:16
I think we could probably use the `create` group for this? So something like `dojo create tutorial`, are we keeping all the tutorials in a single repository? With that command we could have `dojo create tutorial --list` that reports all available tutorials and their description?

Because for me we wouldn't really want to support this via a command like this `dojo copy app -git git@github.com:edhager/myCoolDojoApp.git` because isn't that just a `git clone....` with maybe an install baked in (seems overkill to be that flexible)

**Comment by rishson** [comment] 2017-02-03 10:42
So i was thinking of a package `cli-tutorial` that had:

`dojo tutorial` - default command (lists installed tutorials)
`dojo tutorial get tutorialName` - fetches a tutorial
`dojo tutorial delete tutorialName` - deletes the tutorial

**Comment by tomdye** [comment] 2017-02-03 10:43
@rishson don't forget that if `get` and `delete` are arguments, it's `-get` and `-delete`. Unless you're implying that they should be stand-alone commands.

**Comment by agubler** [comment] 2017-02-03 10:46
I don't think that `tutorial` fits into the category of a group personally and am very much in support of using the `create` group.

Also I don't think we really need to support deleting a tutorial because that seems silly (and also something that I wouldn't want a command to do).

So something like:

`dojo create tutorial --list` - lists all available tutorials
`dojo create tutorial --name tutorial-1` - creates tutorial one (perhaps support installing by `id`)

and I'm not sure we need much more.

**Comment by matt-gadd** [comment] 2017-02-03 11:06
Why do we need another management system on top of the management and discovery system that are `commands` already? if we we make each a tutorial as a command, we already have the mechanisms to:

* add
* remove
* list
* configure

A `group` is normally a verb, e.g `build`, `test`, `create`. So how about we have a `learn` group? Using the command discovery you will then be able to ship a set of commands (just ship a meta-package that contains all the other tutorial commands as a dependency - like how babels presets work).

**Comment by agubler** [comment] 2017-02-03 11:32
A reasonable question @matt-gadd that does seem like a good use of the CLI and in the spirit of how it was designed. And will actually result in creating tutorials being cleaner, easier and less effort. 

Additionally there are similarities between the installing a tutorial and using `create app` so I expect there will be some overlap in functionality that they could all share.

**Comment by dylans** [comment] 2017-02-03 12:57
I think you probably want a command to get all tutorials as well... if I'm planning to do the entire series, why make me install them one by one.

**Comment by agubler** [comment] 2017-02-03 13:00
For me I don't think you'd want to create all the tutorial directories at once, but certainly they'd all be available from the single command (without having to do multiple npm installs) as they'd already be installed via the meta package matt described.

**Comment by matt-gadd** [comment] 2017-02-04 18:53
@dylans as I said, you can publish a meta package with them all. and this way you can ship granular optional/non-official tutorials also.

**Comment by eheasley** [comment] 2017-03-22 18:29
This was discussed with @vansimke and we agreed to use a zip and download solution, which will bypass the need for action with this issue.  Thank you!

**Comment by dylans** [comment] 2017-03-22 23:01
This should not have been closed. I believe we decided on zip and download for beta 1 due to time constraints, but for beta 2, I believe this should be done the "right way" (via cli).

**Comment by kitsonk** [comment] 2017-10-10 10:21
I am moving this to post release of Dojo 2.0.  We have enough to do and we can improve the usability of the tutorials post the release of 2.0.

**Closed** 2019-07-03 07:35 UTC
Labels: discussion, dojo-2.1, enhancement
